/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HtetPhyoNaing;

/**
 *
 * @author GIC
 */
public class Practice extends javax.swing.JPanel {

    /**
     * Creates new form Practice
     */
    public Practice() {
        initComponents();
        this.setSize(820, 658);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxChooseAllOrFav = new javax.swing.JComboBox<>();
        labelChooseTypeOfPractice = new javax.swing.JLabel();
        labelChooseTypeOfPractice1 = new javax.swing.JLabel();
        cboxLessonInCreateVocabulary = new javax.swing.JComboBox<>();
        cboxLessonInCreateVocabulary1 = new javax.swing.JComboBox<>();
        labelChooseTypeOfPractice2 = new javax.swing.JLabel();
        labelChooseTypeOfPractice3 = new javax.swing.JLabel();
        btnPracticeVoca = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(820, 658));

        cboxChooseAllOrFav.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cboxChooseAllOrFav.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Vocabularies", "Only Favorites" }));
        cboxChooseAllOrFav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboxChooseAllOrFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxChooseAllOrFavActionPerformed(evt);
            }
        });

        labelChooseTypeOfPractice.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        labelChooseTypeOfPractice.setText("Choose type of practice");

        labelChooseTypeOfPractice1.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        labelChooseTypeOfPractice1.setText("From");

        cboxLessonInCreateVocabulary.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cboxLessonInCreateVocabulary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lesson 1", "Lesson 2", "Lesson 3", "Lesson 4", "Lesson 5", "Lesson 6", "Lesson 7", "Lesson 8", "Lesson 8", "Lesson 9", "Lesson 10", "Lesson 11", "Lesson 12", "Lesson 13", "Lesson 14", "Lesson 15", "Lesson 16", "Lesson 17", "Lesson 18", "Lesson 19", "Lesson 20", "Lesson 21", "Lesson 22", "Lesson 23", "Lesson 24", "Lesson 25" }));
        cboxLessonInCreateVocabulary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboxLessonInCreateVocabulary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxLessonInCreateVocabularyActionPerformed(evt);
            }
        });

        cboxLessonInCreateVocabulary1.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cboxLessonInCreateVocabulary1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lesson 1", "Lesson 2", "Lesson 3", "Lesson 4", "Lesson 5", "Lesson 6", "Lesson 7", "Lesson 8", "Lesson 8", "Lesson 9", "Lesson 10", "Lesson 11", "Lesson 12", "Lesson 13", "Lesson 14", "Lesson 15", "Lesson 16", "Lesson 17", "Lesson 18", "Lesson 19", "Lesson 20", "Lesson 21", "Lesson 22", "Lesson 23", "Lesson 24", "Lesson 25" }));
        cboxLessonInCreateVocabulary1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboxLessonInCreateVocabulary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxLessonInCreateVocabulary1ActionPerformed(evt);
            }
        });

        labelChooseTypeOfPractice2.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        labelChooseTypeOfPractice2.setText("To");

        labelChooseTypeOfPractice3.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        labelChooseTypeOfPractice3.setText("If you choose same lesson for both range, you will be practicing only for that lesson.");

        btnPracticeVoca.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        btnPracticeVoca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HtetPhyoNaing/Resources/Images/img-btn-start-practice.png"))); // NOI18N
        btnPracticeVoca.setText("Start");
        btnPracticeVoca.setBorder(null);
        btnPracticeVoca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPracticeVoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPracticeVocaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelChooseTypeOfPractice, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxChooseAllOrFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxLessonInCreateVocabulary, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelChooseTypeOfPractice1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboxLessonInCreateVocabulary1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPracticeVoca, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelChooseTypeOfPractice2)))
                    .addComponent(labelChooseTypeOfPractice3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelChooseTypeOfPractice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxChooseAllOrFav, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelChooseTypeOfPractice1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxLessonInCreateVocabulary, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelChooseTypeOfPractice2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPracticeVoca, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(cboxLessonInCreateVocabulary1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelChooseTypeOfPractice3)
                .addContainerGap(487, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboxChooseAllOrFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxChooseAllOrFavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxChooseAllOrFavActionPerformed

    private void cboxLessonInCreateVocabularyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxLessonInCreateVocabularyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxLessonInCreateVocabularyActionPerformed

    private void cboxLessonInCreateVocabulary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxLessonInCreateVocabulary1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxLessonInCreateVocabulary1ActionPerformed

    private void btnPracticeVocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPracticeVocaActionPerformed
        
    }//GEN-LAST:event_btnPracticeVocaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPracticeVoca;
    private javax.swing.JComboBox<String> cboxChooseAllOrFav;
    private javax.swing.JComboBox<String> cboxLessonInCreateVocabulary;
    private javax.swing.JComboBox<String> cboxLessonInCreateVocabulary1;
    private javax.swing.JLabel labelChooseTypeOfPractice;
    private javax.swing.JLabel labelChooseTypeOfPractice1;
    private javax.swing.JLabel labelChooseTypeOfPractice2;
    private javax.swing.JLabel labelChooseTypeOfPractice3;
    // End of variables declaration//GEN-END:variables
}
